---
- name: Install Docker
  package:
    name: "docker.io"
    state: present
  become: true

- name: Enable Docker
  service:
    name: docker
    state: started
    use: service
    enabled: true
  become: true

- name: Install VirtualBox
  package:
    name: "virtualbox"
    state: present
  become: true

- name: Install VS Code
  block:
    - name: Install VS Code Repo
      apt:
        deb: https://go.microsoft.com/fwlink/?LinkID=760868
        state: present
      become: true

    - name: Install VS Code
      apt:
        name: code
        update_cache: true
      become: true
